---
- name: Install rcron
  apt:
    name: rcron
    state: present

- name: Create conf directory
  file:
    path: /etc/rcron
    state: directory
    mode: 0755

- name: Deploy rcron configuration
  template:
    src: rcron.conf
    dest: /etc/rcron/rcron.conf
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0640

- name: Create state directory
  file:
    path: /var/run/rcron/
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0755

- name: Create rcron state file (because it is not created on-the-fly)
  template:
    src: state
    dest: /var/run/rcron/state
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0666
